---
kind: pipeline
type: docker
name: droneTest

platform:
  os: linux
  arch: amd64

clone:
  disable: true
steps:
  - name: build_exe
    pull: if-not-exists
    image: golang:1.18
    commands:
      - export GOOS=linux
      - export GOARCH=amd64
      - export CGO_ENABLED=0
      - echo hello
    # volumes:
    #   - name: gocache
    #     path: /root/.cache/go-build
    #   - name: gomodcache
    #     path: /go/pkg/mod